Setup modules directory
open-ead/nnheaders pull request #13
Opened 2022-10-22 16:08 UTC by ThePixelGamer

2022-10-22 22:11 UTC, leoetlino commented
On second thought, I think we should have NintendoSDK and NintendoWare folders under modules (and maybe even get rid of the top-level "modules" directory entirely):

* src
  * NintendoSDK
    * nnSdk
    * gfx
    * libcurl
  * NintendoWare
    * g3d
    * atk
    * vfx
    * ui2d
    * font

(inspired by https://discord.com/channels/688807550715560050/794951602396987432/1030560220310671432, but without the top-level 'Nintendo' dir because it's unlikely we'll have Havok in here)

2022-10-22 22:14 UTC, ThePixelGamer commented
In that case where should I move nvn?

2022-10-22 22:18 UTC, leoetlino commented
NintendoSDK/nvn, probably?

Unrelated, but there's also NintendoSDK/movie

2022-10-25 17:04 UTC, leoetlino requested changes

2022-10-25 17:04 UTC, leoetlino commented on CMakeLists.txt
> +  src/nvn/nvnInit.cpp
```suggestion
  src/NintendoSDK/nvn/nvnInit.cpp
```

2022-10-25 17:14 UTC, leoetlino approved these changes

2022-10-25 17:14 UTC, merged