Changes from `smo-lunakit`
open-ead/nnheaders pull request #27
Opened 2024-02-29 21:52 UTC by MonsterDruide1

Adds all infos collected in the context of the mod `smo-lunakit`, by @Amethyst-szs, but probably also contains changes originally made by @CraftyBoss.

List of changes/"overrides" currently available at https://github.com/MonsterDruide1/smo-lunakit/tree/stable/lib/custom/nn, although this link will be invalid after this PR has been merged.

2024-03-13 21:51 UTC, leoetlino commented on include/nn/socket.h
> -#if NN_SDK_VER >= NN_MAKE_VER(7, 0, 0)
backward compatibility?

2024-03-13 21:54 UTC, leoetlino requested changes

2024-03-13 21:54 UTC, leoetlino commented on include/nn/vfx/Resource.h
> +    void GetPrimitive(ulong) const;
ulong should probably be size_t (or less likely, unsigned long / u64).

2024-03-15 20:42 UTC, MonsterDruide1 commented on include/nn/vfx/Resource.h
> +    Resource(gfx::TDevice<gfx::ApiVariationNvn8>*, Heap*, void*,
There is an [NVNdevice](https://code.botw.link/uking/uking/lib/NintendoSDK/include/nvn/nvn.h.html#NVNdevice), which is not the correct typedef though. It seems like so far, `TDevice<ApiVariationNvn8>` has been used manually (for example [here](https://code.botw.link/uking/uking/lib/NintendoSDK/include/nn/gfx/gfx_Interoperation-api.nvn.8.h.html))

2024-03-15 21:35 UTC, MonsterDruide1 commented
I just noticed that `swkbd.h` was already included in the repo, so I merged the new file into the existing one.

2024-03-15 23:40 UTC, ThePixelGamer commented on include/nn/vfx/Resource.h
> +    Resource(gfx::TDevice<gfx::ApiVariationNvn8>*, Heap*, void*,
https://github.com/open-ead/nnheaders/blob/master/include/nn/gfx/gfx_Types.h#L10

2024-03-16 11:59 UTC, MonsterDruide1 commented on include/nn/vfx/Resource.h
> +    Resource(gfx::TDevice<gfx::ApiVariationNvn8>*, Heap*, void*,
Ah, alright - adjusted accordingly, thanks for the reference!

2024-03-18 01:49 UTC, leoetlino reviewed
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/27)* status: 5 of 18 files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1 and @ThePixelGamer)

___
*[`include/nn/swkbd/swkbd.h` line 7 at r2](https://reviewable.io/reviews/open-ead/nnheaders/27#-NtEEJJK1aepPfMJv6vl:-NtEEJJK1aepPfMJv6vm:b10n647) ([raw file](https://github.com/open-ead/nnheaders/blob/cb6449b86012e890cb8a1e097d72f8c34480b796/include/nn/swkbd/swkbd.h#L7)):*
> ```objc
> 
> namespace nn::applet {
> enum class ExitReason { Normal = 0, Canceled = 1, Abnormal = 2, Unexpected = 10 };
> ```

could you move this into an applet header?
___
*[`include/nn/swkbd/swkbd.h` line 167 at r2](https://reviewable.io/reviews/open-ead/nnheaders/27#-NtEEoa14qt6MBqXQLAy:-NtEEoa14qt6MBqXQLAz:b-iap3vw) ([raw file](https://github.com/open-ead/nnheaders/blob/cb6449b86012e890cb8a1e097d72f8c34480b796/include/nn/swkbd/swkbd.h#L167)):*
> ```objc
> ulong GetRequiredWorkBufferSize(bool);
> ulong GetRequiredStringBufferSize();
> nn::applet::ExitReason getExitReason();
> ```

GetExitReason (uppercase G)?


<!-- Sent from Reviewable.io -->

2024-04-10 16:31 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/27)* status: 4 of 19 files reviewed, 3 unresolved discussions (waiting on @leoetlino and @ThePixelGamer)

___
*[`include/nn/swkbd/swkbd.h` line 7 at r2](https://reviewable.io/reviews/open-ead/nnheaders/27#-NtEEJJK1aepPfMJv6vl:-Nv7qFHECkffZ6a8U-D7:b-896fix) ([raw file](https://github.com/open-ead/nnheaders/blob/cb6449b86012e890cb8a1e097d72f8c34480b796/include/nn/swkbd/swkbd.h#L7)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

could you move this into an applet header?
</blockquote></details>

Done.
___
*[`include/nn/swkbd/swkbd.h` line 167 at r2](https://reviewable.io/reviews/open-ead/nnheaders/27#-NtEEoa14qt6MBqXQLAy:-Nv7qFnE63OFwJCQzL2k:b-896fix) ([raw file](https://github.com/open-ead/nnheaders/blob/cb6449b86012e890cb8a1e097d72f8c34480b796/include/nn/swkbd/swkbd.h#L167)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

GetExitReason (uppercase G)?
</blockquote></details>

Done.
___
*[`include/nn/vfx/Resource.h` line 53 at r1](https://reviewable.io/reviews/open-ead/nnheaders/27#gh-1523960376:-Nv7qHujEGcdE-ePm1AK:b-896fix) ([raw file](https://github.com/open-ead/nnheaders/blob/6aad273f830c314bf721f0258ca1a9dca9139057/include/nn/vfx/Resource.h#L53)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

ulong should probably be size_t (or less likely, unsigned long / u64).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-22 00:24 UTC, leoetlino approved these changes
> Reviewed 12 of 16 files at r1, 1 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/27)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1 and @ThePixelGamer)

___
*[`include/nn/diag.h` line 28 at r3](https://reviewable.io/reviews/open-ead/nnheaders/27#-Nw2AWqnCe5XPLpS33EX:-Nw2AWqnCe5XPLpS33EY:b-7td3tf) ([raw file](https://github.com/open-ead/nnheaders/blob/f2846888854e55e964a2ec4834912cda75dd8c98/include/nn/diag.h#L28)):*
> ```objc
> 
> // MODULE / SYMBOL
> u64 GetSymbolName(char* name, u64 nameSize, u64 addr);
> ```

I think this should probably be taking a size_t nameSize and returning a size_t instead of u64. addr should probably be uintptr_t
___
*[`include/nn/fs/fs_directories.h` line 34 at r3](https://reviewable.io/reviews/open-ead/nnheaders/27#-Nw2Axf83bXUcpPHnH71:-Nw2Axf83bXUcpPHnH72:b-e0y07i) ([raw file](https://github.com/open-ead/nnheaders/blob/f2846888854e55e964a2ec4834912cda75dd8c98/include/nn/fs/fs_directories.h#L34)):*
> ```objc
>     path: Path to path to create.
> */
> Result CreateDirectory(char const* path);
> ```

const char*


<!-- Sent from Reviewable.io -->

2024-04-25 19:58 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/27)* status: all files reviewed, 2 unresolved discussions (waiting on @leoetlino and @ThePixelGamer)

___
*[`include/nn/diag.h` line 28 at r3](https://reviewable.io/reviews/open-ead/nnheaders/27#-Nw2AWqnCe5XPLpS33EX:-NwLp-0C5kgbhnDAzGRe:bdr74g7) ([raw file](https://github.com/open-ead/nnheaders/blob/f2846888854e55e964a2ec4834912cda75dd8c98/include/nn/diag.h#L28)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I think this should probably be taking a size_t nameSize and returning a size_t instead of u64. addr should probably be uintptr_t
</blockquote></details>

I don't know the difference between those types, so you might be right - I just worked based on the symbols, not sure if the types you suggested "compile back" to the types I annotated here. Changed it though.
___
*[`include/nn/fs/fs_directories.h` line 34 at r3](https://reviewable.io/reviews/open-ead/nnheaders/27#-Nw2Axf83bXUcpPHnH71:-NwLpVDUE2AKi68DI-gE:bruiwv6) ([raw file](https://github.com/open-ead/nnheaders/blob/f2846888854e55e964a2ec4834912cda75dd8c98/include/nn/fs/fs_directories.h#L34)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

const char*
</blockquote></details>

Adjusted here and in a few other files I encountered.


<!-- Sent from Reviewable.io -->

2024-05-06 00:00 UTC, leoetlino approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/27)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ThePixelGamer)



<!-- Sent from Reviewable.io -->

2024-05-06 00:06 UTC, ThePixelGamer approved these changes
LGTM

2024-05-06 00:11 UTC, merged