Fix syntax error in nn/socket.h
open-ead/nnheaders pull request #34
Opened 2024-09-06 08:29 UTC by Pistonight

2024-09-06 11:28 UTC, LynxDev2 commented
Could you also fix the include errors? For most projects netdb.h and sys/socket.h don’t exist

2024-09-06 17:14 UTC, Pistonight commented
> Could you also fix the include errors? For most projects netdb.h and sys/socket.h don’t exist

I believe those are part of libnx include. You need to add `-I$(DEVKITPRO)/libnx/include` to the compiler flags.
I had some other include errors not seeing BSD types which I am not sure why, but they were fixable with a hack
```c++
#undef __BSD_VISIBLE
#define __BSD_VISIBLE 1
#include <netinet/in.h> // for socketaddr_in
#include <nn/socket.h>
```

2024-09-06 17:19 UTC, LynxDev2 commented
Yeah, but like every single mod overrides that header with a different one. Nin didn’t use libnx so we shouldn’t either and none of the decomp projects I’ve worked on use libnx

2024-09-06 17:35 UTC, Pistonight commented
> Yeah, but like every single mod overrides that header with a different one. Nin didn’t use libnx so we shouldn’t either and none of the decomp projects I’ve worked on use libnx

Fair, I replaced includes with forward declare

2024-09-06 21:59 UTC, leoetlino commented
>  Could you also fix the include errors? For most projects netdb.h and sys/socket.h don’t exist

This doesn't sound right (at least for a properly set up project) - netdb.h and sys/socket.h are libc headers. Official titles use musl which does come with those headers.

2024-09-06 22:02 UTC, leoetlino requested changes
You can't forward declare (at least) some of these types - for instance musl defines fd_set as a typedef of an anonymous struct so forward declaring it as a struct is incorrect. Just include the headers and don't cater to people who have broken setups.

2024-09-06 22:15 UTC, Pistonight commented
> You can't forward declare (at least) some of these types - for instance musl defines fd_set as a typedef of an anonymous struct so forward declaring it as a struct is incorrect. Just include the headers and don't cater to people who have broken setups.

I was wondering about fd_set since I saw it as typedef. Will revert those then

2024-09-06 22:27 UTC, Pistonight commented
There's an error in `in_addr`. Should I include netinet/in.h or forward declare it, or just leave as is?

2024-09-07 05:19 UTC, LynxDev2 commented
@MonsterDruide1 You said in DMs that at least netdb.h shouldn’t be included here and that this header doesn’t work for most projects. Could you give a solution?

2024-09-08 22:06 UTC, leoetlino approved these changes

2024-09-08 22:06 UTC, merged